<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-G1FQHVUJ" failures="0" tests="3" name="API.RunCucumberTest" time="4.412" errors="2" timestamp="2021-02-09T16:07:45 IST" skipped="0">
  <testcase classname="API.RunCucumberTest" name="runScenario" time="4.380">
    <error message="error - 1" type="utilities.myAssertionException">
      <![CDATA[utilities.myAssertionException: error - 1
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="API.RunCucumberTest" name="runScenario" time="0.014"/>
  <system-out/>
  <testcase classname="API.RunCucumberTest" name="runScenario" time="0.018">
    <error message="error - 2" type="utilities.myAssertionException">
      <![CDATA[utilities.myAssertionException: error - 2
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- API.RunCucumberTest -->
